# Implement your install deployment tasks here
# -------------------------------------------------

- name: install
  become: true
  delegate_to: "{{ exporter_host }}"
  block:
    - name: build Badgerd SDWireC
      ansible.builtin.import_tasks: build_sdwire.yml
      when: install_sdwire | bool == true

    - name: build YKUSH 
      ansible.builtin.import_tasks: build_ykush.yml
      when: install_ykush | bool == true

    - name: pull the latest jumpstarter container
      become: true
      shell: podman pull {{ container_image }}

    # add the oc client and authenticate the exporter host

    - name: install the oc client
      become: true
      shell: |
        curl {{ oc_client_url }} -o oc.tar.gz
        tar xvf oc.tar.gz
        mv oc /usr/local/bin/
        mv kubectl /usr/local/bin/
        rm oc.tar.gz
      args:
        chdir: "/tmp"

    - name: authenticate to the cluster (normal user)
      become: false
      shell: oc login https://api.{{ cluster_base_domain }}:6443 --username={{ default_admin_user }} --password={{ default_admin_password }} --insecure-skip-tls-verify=true

    - name: authenticate to the cluster (sudo user)
      become: true
      shell: oc login https://api.{{ cluster_base_domain }}:6443 --username={{ default_admin_user }} --password={{ default_admin_password }} --insecure-skip-tls-verify=true

       # patch the .kube/config because of the wrong permissions
    - name: patch the .kube/config
      become: true
      shell: chmod 0744 /root/.kube/config