# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: post_install
  become: true
  delegate_to: "{{ exporter_host }}"
  block:
    # create the default exporters

    - name: create the default exporters
      become: true
      shell: |
        podman run --rm -ti --net=host --privileged \
          -v /run/udev:/run/udev -v /dev:/dev \
          -v /root/.kube/config:/root/.kube/config \
          -v "{{ work_dir }}/{{ exporter_dir }}:/opt/app-root/src/workspace" \
          {{ container_image }} \
          /bin/bash -c "jmp admin create exporter outpost-{{ item }} -n {{ platform_jumpstarter_namespace }} \
            --label platform=rpi4 --label type=outpost \
            --save --out /opt/app-root/src/workspace/outpost-{{ item }}-exporter.yaml"
      args:
        chdir: "{{ work_dir }}"
      with_items:
        - "default"

    - name: read the exporter config
      slurp:
        src: "{{ work_dir }}/{{ exporter_dir }}/outpost-default-exporter.yaml"
      register: exporter_file

    - name: parse the exporter config
      set_fact:
        exporter_config: "{{ exporter_file.content | b64decode | from_yaml }}"

    - name: patch the exporter configs
      become: true
      ansible.builtin.template:
        src: "../templates/{{ item }}-exporter.yaml.j2"
        dest: "{{ work_dir }}/{{ exporter_dir }}/outpost-{{ item }}-exporter.yaml"
        mode: "0755"
      with_items:
        - "default"

    # create systemd services for the exporters

    - name: create start scripts
      become: true
      ansible.builtin.template:
        src: "../templates/default-exporter-start.sh.j2"
        dest: "/usr/local/bin/outpost-{{ item }}-exporter.start"
        mode: "0755"
      with_items:
        - "default"

    - name: create stop scripts
      become: true
      ansible.builtin.template:
        src: "../templates/default-exporter-stop.sh.j2"
        dest: "/usr/local/bin/outpost-{{ item }}-exporter.stop"
        mode: "0755"
      with_items:
        - "default"

    - name: create systemd scripts
      become: true
      ansible.builtin.template:
        src: "../templates/default-exporter.service.j2"
        dest: "/etc/systemd/system/outpost-{{ item }}-exporter.service"
        mode: "0755"
      with_items:
        - "default"

    - name: refresh the systemd daemon
      become: true
      shell: systemctl daemon-reload

    - name: enable the systemd services
      become: true
      shell: |
        systemctl enable outpost-{{ item }}-exporter.service
        systemctl start outpost-{{ item }}-exporter.service
      with_items:
        - "default"
