---
# defaults

# bare-metal worker node
aws_metal_instance_type: "m6g.metal" # 64 vCPU, 256 GiB RAM
aws_metal_ami_id: "ami-02f30107e3441227b" # ARM, us-east-2
aws_metal_subregion: "b" # a, b, c

aws_metal_instance_count: 1 # number of replicas per availability zone
aws_metal_volume_size: 120
aws_metal_volume_type: "gp3"
aws_metal_vcpu: 64
aws_metal_gpu: 0
aws_metal_memory: 262144

# cnv operator
cnv_operator_name: "kubevirt-hyperconverged"
cnv_operator_subscription_name: "kubevirt-hyperconverged"
cnv_operator_deployment_name: "virt-operator"
cnv_subscription_channel: "stable"
cnv_subscription_starting_csv: "kubevirt-hyperconverged-operator.v4.19.1"
cnv_operator_namespace: "openshift-cnv"
cnv_operator_group: "openshift-cnv"
