- name: bootstrap the openshift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE

  tasks:
    - name: gather cluster facts
      include_role:
        name: roles/gather-cluster-facts

    - name: configure certificates
      include_role:
        name: roles/setup-cert-manager

    - name: configure cluster authentication
      include_role:
        name: roles/setup-auth

    - name: install essential devops operators e.g. gitops, pipelines, etc.
      include_role:
        name: roles/setup-devops

    - name: show web console url
      debug:
        msg: "Access the OpenShift web-console here: https://console-openshift-console.apps.{{ cluster_name }}.{{ cluster_domain }}"