- name: Prepare an exporter host
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE
  
  tasks:
    - name: gather facts
      include_role:
        name: roles/gather-cluster-facts

    - name: update/patch/uninstall the outpost configuration
      vars:
        ansible_user: autom8te
        ansible_ssh_private_key_file: ~/.ssh/autom8te
        exporter_host: "outpost.local"
      include_role:
        name: roles/config-outpost
