- name: remove the OpenShift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "UNINSTALL" # INSTALL, UNINSTALL, UPDATE

  tasks:
    - name: destroy the openshift cluster
      include_role:
        name: roles/install-openshift-aws
      when: cloud_provider == "aws"
