- name: lifecycle the openshift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "START" # START, STOP, UNINSTALL, UPDATE

  tasks:
    - name: start the openshift cluster
      include_role:
        name: roles/lifecycle-cluster

    - name: show web console url
      debug:
        msg: "Access the OpenShift web-console here: https://console-openshift-console.apps.{{ cluster_name }}.{{ cluster_domain }}"