# Implement your install deployment tasks here
# -------------------------------------------------

# add the arm machine sets to the cluster
- name: add the arm machine sets
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_arm_a.yml.j2"
    - "machineset_arm_b.yml.j2"
    - "machineset_arm_c.yml.j2"

# FIXME add labels to the ARM worker nodes

# FIXME add labels to the secorndary worker nodes (amd64)

# configure the cluster to use a Let's Encrypt certificate
- name: install cert operator
  import_tasks: install_cert_operator.yml
