# Implement your initial tasks here
# -------------------------------------------------

- name: set cluster facts
  set_fact:
    cluster_fqn: "{{ cluster_name }}-{{ cloud_provider }}"

- name: set the local kubeconfig location
  set_fact:
    local_kubeconfig_file: "~/.kube/{{ cluster_fqn }}"
    
- name: create .env file
  template:
    src: "roles/install-openshift/templates/env-{{ cloud_provider }}.j2"
    dest: "{{ openshift_install_dir }}/.env-{{ cluster_fqn }}.sh"

- name: create azure credentials file
  when: cloud_provider == "azure"
  template:
    src: "roles/install-openshift/templates/azure_credentials.json.j2"
    dest: "~/.azure/osServicePrincipal.json"