all:
  # default values controlling the behavior of the bootstrap process
  vars:
    remove_kubeadmin: False # True
    remove_selfprovisioning: True
    
    # keys
    cluster_ssh_key: "$HOME/.ssh/rhadp" # use existing keypair, or generate a new one if it does not exist
    pull_secret_file: "inventory/pull-secret.txt" # place the pull secret at this loacation

    # local installation directory
    openshift_install_dir: "$HOME/.openshift" # local directory where the cluster metadata will be stored