all:
  # default values to configure the development platform deployment
  vars:
    # resource prefix
    rhadp_prefix: "rhadp" # used in e.g. namespace creation

    # default namespaces
    gitops_namespace: "openshift-gitops" # the system wide GitOps instance
    keycloak_namespace: "keycloak"
    vault_namespace: "vault"    
    # default namespaces
    gitops_namespace: "openshift-gitops" # the system wide GitOps instance
    keycloak_namespace: "keycloak"
    vault_namespace: "vault"    

    # default openshift groups
    cluster_admin_group: "cluster-admins"
    platform_admin_group: "platform-admins"
    platform_user_group: "platform-users"

    # default repo for all the developer hub templates
    rhadp_templates_repo_url: "https://github.com/rhadp/rhadp-templates"
    rhadp_templates_repo_revision: "main"

    # default repo for all the GitOps apps
    rhadp_gitops_repo_url: "https://github.com/rhadp/rhadp-manifests"
    rhadp_gitops_repo_revision: "main"

    # default repo for all the Helm Charts
    rhadp_helm_repo_url: "https://github.com/rhadp/rhadp-manifests"
    rhadp_helm_repo_revision: "main"

    # remove the kubeadmin user and the self-provisioning role
    remove_kubeadmin: True
    remove_selfprovisioning: True

    # local directory where the cluster metadata will be stored
    cluster_metadata_dir: "$HOME/.openshift"

    # where to store the openshift-install binary
    openshift_install_dir: "bin"

    # key used for the cluster nodes
    cluster_ssh_key_dir: "$HOME/.ssh" # use existing keypair, or generate a new one if it does not exist