# Implement your initial tasks here
# -------------------------------------------------

- name: set cluster facts
  set_fact:
    cluster_fqn: "{{ cluster_name }}-{{ cloud_provider }}"

- name: set the local kubeconfig location
  set_fact:
    local_kubeconfig_file: "~/.kube/{{ cluster_fqn }}"

# extract some basic cluster information
- name: get DNS information
  k8s_info:
    api_version: config.openshift.io/v1
    kind: dns
    name: cluster
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_cluster_dns

- name: set base domain (all clouds)
  set_fact:
    cluster_base_domain: "{{ r_cluster_dns.resources.0.spec.baseDomain }}"

- name: set public zone id (aws)
  when: cloud_provider == "aws"
  set_fact:
    cluster_public_zone_id: "{{ r_cluster_dns.resources.0.spec.publicZone.id }}" # Route53 hosted zone ID

- name: set public zone id (azure)
  when: cloud_provider == "azure"
  set_fact:
    cluster_public_zone_id: "{{ r_cluster_dns.resources.0.spec.publicZone.id.split('/')[-1] }}" # Azure DNS zone ID

- name: set public zone id (gcp)
  when: cloud_provider == "gcp"
  set_fact:
    cluster_public_zone_id: "{{ r_cluster_dns.resources.0.spec.publicZone.id }}" # Google Cloud DNS zone ID