# Implement your install deployment tasks here
# -------------------------------------------------

- name: create namespaces
  k8s:
    kind: Namespace
    name: "{{ item }}"
    definition:
      metadata:
        labels:
          argocd.argoproj.io/managed-by: openshift-gitops
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  with_items:
    - "{{ platform_jumpstarter_namespace }}"
    - "{{ platform_exporter_namespace }}"

- name: create cluster role and role binding
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - jumpstarter-cluster-role.yml
    - jumpstarter-cluster-role-binding.yml.j2

- name: create jumpstarter application
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - jumpstarter-cluster-role-binding-oidc-reviewer.yml
    - jumpstarter-application.yml.j2

- name: wait for the jumpstarter application to be ready
  k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: jumpstarter
    namespace: "{{ gitops_namespace }}"
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_application
  retries: 180
  delay: 10
  until:
    - r_application.resources | length > 0
    - r_application.resources[0].status is defined
    - r_application.resources[0].status.sync is defined
    - r_application.resources[0].status.sync.status is defined
    - r_application.resources[0].status.sync.status == 'Synced'

- name: create qemu exporter assets
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml_all }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - qemu-exporter-role-binding.yaml.j2
    - qemu-exporter-statefulset.yaml.j2
    - qemu-exporter-client.yaml.j2