# Implement your install deployment tasks here
# -------------------------------------------------

- name: create platform gitops instance to bootstrap the platform
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - bootstrap-project.yml.j2
    - bootstrap-app.yml.j2