# Implement your install deployment tasks here
# -------------------------------------------------

- name: create devspaces instance
  when: rhadp_deploy_devspaces | bool
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - devspaces-github-oauth-config.yml.j2
    - devspaces-fuse-overlay.yml.j2
    - devspaces-instance.yml.j2