# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: prepare devspaces installation
  when: rhadp_deploy_devspaces | bool == True
  block:
    - name: install devspaces operator
      include_role:
        name: roles/install-operator
      vars:
        operator_name: "devspaces"
        operator_subscription_name: "devspaces"
        subscription_channel: "{{ devspaces_subscription_channel }}"
        subscription_starting_csv: "{{ devspaces_subscription_starting_csv }}"
        operator_deployment_name: "devspaces-operator"
        create_operator_namespace: false
        create_operator_group: false

    - name: create devspaces namespace
      k8s:
        kind: Namespace
        name: "{{ platform_devspaces_namespace }}"
        state: present
        apply: yes
        kubeconfig: "{{ local_kubeconfig_file }}"

- name: prepare developer hub installation
  when: rhadp_deploy_developer_hub | bool == True
  block:
    - name: install developer hub operator
      include_role:
        name: roles/install-operator
      vars:
        operator_name: "rhdh"
        operator_subscription_name: "rhdh"
        subscription_channel: "{{ devhub_subscription_channel }}"
        subscription_starting_csv: "{{ devhub_subscription_starting_csv }}"
        operator_namespace: "rhdh-operator"
        operator_group_name: "rhdh-operator"
        create_operator_namespace: true
        create_operator_group: true

    - name: create developer hub namespace
      k8s:
        kind: Namespace
        name: "{{ platform_developer_hub_namespace }}"
        state: present
        apply: yes
        kubeconfig: "{{ local_kubeconfig_file }}"


  