# Implement your install deployment tasks here
# -------------------------------------------------

# add the 2nd machine sets to the cluster
- name: configure additional machine sets
  when: setup_arm_worker_nodes | bool == true
  import_tasks: install_machineset.yml

# add the bare-metal worker node to the cluster
- name: configure the 'metal' cluster topology
  when: setup_baremetal_worker_node | bool == true
  import_tasks: install_metal.yml

# setup virtualization (currently aws only)
- name: create cnv
  when: setup_virtualization | bool == true and setup_baremetal_worker_node | bool == true and cloud_provider == "aws"
  block:
  - name: install cnv operator
    include_role:
      name: roles/install-operator
    vars:
      operator_name: "{{ cnv_operator_name }}"
      operator_subscription_name: "{{ cnv_operator_subscription_name }}"
      subscription_channel: "{{ cnv_subscription_channel }}"
      subscription_starting_csv: "{{ cnv_subscription_starting_csv }}"
      operator_deployment_name: "{{ cnv_operator_deployment_name }}"
      operator_namespace: "{{ cnv_operator_namespace }}"
      operator_group_name: "{{ cnv_operator_group }}"
      create_operator_namespace: true
      create_operator_group: true
      manage_all_namespaces: false

  - name: create cnv
    k8s:
      definition: "{{ lookup('template', item) | from_yaml }}"
      state: present
      apply: yes
      kubeconfig: "{{ local_kubeconfig_file }}"
    loop:
      - hyperconverged.yml.j2