# Implement your install deployment tasks here
# -------------------------------------------------

# add the 2nd machine sets to the cluster

- name: add the arm machine sets (aws)
  when: setup_arm_worker_nodes and cloud_provider == "aws"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_aws_arm_a.yml.j2"
    - "machineset_aws_arm_b.yml.j2"
    - "machineset_aws_arm_c.yml.j2"

- name: add the arm machine sets (azure)
  when: setup_arm_worker_nodes and cloud_provider == "azure"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_azure_arm_a.yml.j2"

- name: add the arm machine sets (gcp)
  when: setup_arm_worker_nodes and cloud_provider == "gcp"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_gcp_arm_a.yml.j2"
    - "machineset_gcp_arm_b.yml.j2"
    - "machineset_gcp_arm_f.yml.j2"
