# Implement your install deployment tasks here
# -------------------------------------------------
    
- name: download the github runner
  delegate_to: "{{ instance_public_ip }}"
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    curl -o actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz \
      -L https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz

    tar xzf ./actions-runner-linux-arm64-{{ github_runner_version }}.tar.gz

- name: change file permissions
  delegate_to: "{{ instance_public_ip }}"
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    chmod -R "0755" *

- name: configure the github runner
  delegate_to: "{{ instance_public_ip }}"
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    RESPONSE=$(curl -s -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer {{ github_api_pat }}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/orgs/{{ github_org }}/actions/runners/registration-token)

    TOKEN=$(echo "$RESPONSE" | jq -r '.token')

    ./config.sh --unattended \
      --url https://github.com/{{ github_org }} \
      --token $TOKEN \
      --name "{{ instance_name }}" \
      --runnergroup "{{ github_runner_group }}" \
      --labels "{{ github_runner_labels }}" \
      --replace

