# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: register the github runner as a service
  delegate_to: "{{ instance_public_ip }}"
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    # fix selinux issues
    # see https://github.com/actions/runner/issues/3186
    chcon system_u:object_r:usr_t:s0 ./svc.sh

    ./svc.sh install

- name: start the github runner
  delegate_to: "{{ instance_public_ip }}"
  become: true
  shell: |
    cd {{ work_dir }}/{{ github_runner_dir }}

    # fix selinux issues
    # see https://github.com/actions/runner/issues/3186
    chcon system_u:object_r:usr_t:s0 ./runsvc.sh

    ./svc.sh start