# Implement your install deployment tasks here
# -------------------------------------------------

# add the bare-metal worker node to the cluster
- name: add the bare-metal machine sets (aws)
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_aws_metal_a.yml.j2"

- name: wait for metal nodes to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    label_selectors:
    - "node.kubernetes.io/instance-type={{ aws_metal_instance_type }}"
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_nodes
  until:
  - r_nodes.resources | length | int == aws_metal_instance_count | int
  delay: 30
  retries: 100
  
# FIXME add labels to the metal worker node