# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: create cnv
  when: setup_virtualization | bool == True and setup_baremetal_worker_node | bool == True and cloud_provider | lower == "aws"
  block:
  # install cnv operator
  - name: install cnv operator
    include_role:
      name: roles/install-operator
    vars:
      operator_name: "{{ cnv_operator_name }}"
      operator_subscription_name: "{{ cnv_operator_subscription_name }}"
      subscription_channel: "{{ cnv_subscription_channel }}"
      subscription_starting_csv: "{{ cnv_subscription_starting_csv }}"
      operator_deployment_name: "{{ cnv_operator_deployment_name }}"
      operator_namespace: "{{ cnv_operator_namespace }}"
      operator_group_name: "{{ cnv_operator_group }}"
      create_operator_namespace: true
      create_operator_group: true
      manage_all_namespaces: false

  - name: create cnv
    k8s:
      definition: "{{ lookup('template', item) | from_yaml }}"
      state: present
      apply: yes
      kubeconfig: "{{ local_kubeconfig_file }}"
    loop:
      - hyperconverged.yml.j2


