# Implement your pre-install deployment tasks here
# -------------------------------------------------

# FIXME: check if the keys already exist, otherwise generate them
- name: generate SSH keys
  openssh_keypair:
    type: rsa
    size: 2048
    path: "{{ cluster_ssh_key }}"

- name: import the public key
  slurp:
    src: "{{ cluster_ssh_key }}.pub"
  register: cluster_ssh_pub_key

- name: debug
  debug:
    msg: "{{ pull_secret_file }}"
    
- name: import pull secret
  slurp:
    src: "{{ pull_secret_file }}"
  register: cluster_pull_secret