# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: generate password hash for admin user
  shell: >-
    htpasswd -nb "{{ default_admin_user }}" "{{ default_admin_password }}"|cut -d: -f2
  register: default_line
  when:
    - default_admin_password is defined

- name: set fact admin user password
  set_fact:
    admin_password_hash: "{{ default_line.stdout }}"
  when:
    - default_admin_password is defined
    - default_line is succeeded
    


