# Implement your install deployment tasks here
# -------------------------------------------------

- name: create ec2 instance
  amazon.aws.ec2_instance:
    instance_type: "{{ vm_instance_type }}"
    image_id: "{{ aws_image_id }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    security_group: "{{ security_group.group_id }}"
    key_name: "{{ ssh_key_name }}"
    network_interfaces:
      - assign_public_ip: true
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ boot_disk_size }}"
          delete_on_termination: true
      - device_name: /dev/sdb
        ebs:
          volume_size: "{{ data_disk_size }}"
          volume_type: gp3
          delete_on_termination: true
    tags:
      Name: "{{ instance_name }}"
    wait: yes
    count: 1
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_default_region }}"
  register: ec2

- name: set public ip and public dns
  set_fact:
    instance_public_ip: "{{ ec2.instances[0].public_ip_address }}"
    instance_public_dns: "{{ ec2.instances[0].public_dns_name }}"
  when: ec2.instances | length > 0

- name: wait for ssh to be available on the new instance
  wait_for:
    host: "{{ instance_public_ip }}"
    port: 22
    delay: 10
    timeout: 300
    state: started

- name: add host key to known_hosts
  known_hosts:
    name: "{{ instance_public_ip }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + instance_public_ip) }}"
    state: present