# Implement your post-install deployment tasks here
# -------------------------------------------------

# extract some basic cluster information
- name: get DNS information
  k8s_info:
    api_version: config.openshift.io/v1
    kind: dns
    name: cluster
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_cluster_dns

- name: set cluster facts (aws)
  when: cloud_provider == "aws"
  set_fact:
    cluster_label: "{{ r_cluster_dns.resources.0.spec.privateZone.tags.Name.split('-')[:-1] | join('-') }}"

- name: set cluster facts (azure)
  when: cloud_provider == "azure"
  set_fact:
    cluster_label: "{{ r_cluster_dns.resources.0.spec.privateZone.id.split('/')[4].split('-')[:-1] | join('-') }}"
    _cluster_label: "{{ r_cluster_dns.resources.0.spec.privateZone.id.split('/')[4].split('-')[:-1] | join('_') }}"

- name: set cluster facts (gcp)
  when: cloud_provider == "gcp"
  set_fact:
    cluster_label: "{{ r_cluster_dns.resources.0.spec.privateZone.id.split('-')[:2] | join('-') }}"

# add the 2nd arm machine sets to the cluster

- name: add the arm machine sets (aws)
  when: setup_arm_worker_nodes and cloud_provider == "aws"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_aws_arm_a.yml.j2"
    - "machineset_aws_arm_b.yml.j2"
    - "machineset_aws_arm_c.yml.j2"

- name: add the arm machine sets (azure)
  when: setup_arm_worker_nodes and cloud_provider == "azure"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_azure_arm_a.yml.j2"

- name: add the arm machine sets (gcp)
  when: setup_arm_worker_nodes and cloud_provider == "gcp"
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - "machineset_gcp_arm_a.yml.j2"
    - "machineset_gcp_arm_b.yml.j2"
    - "machineset_gcp_arm_f.yml.j2"

# FIXME add labels to the ARM worker nodes

# FIXME add labels to the secorndary worker nodes (amd64)

# remove cluster specific assets from the local machine
- name: remove cluster specific assets
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ openshift_install_dir }}/.env-{{ cluster_fqn }}.sh"
