# Implement your uninstall deployment tasks here
# -------------------------------------------------

- name: destroy the openshift cluster
  ignore_errors: true
  shell: |
    source .env-{{ cluster_fqn }}.sh && \
    ./openshift-install destroy cluster --dir="{{ cluster_metadata_dir }}/{{ cluster_fqn }}"
  args:
    chdir: "{{ openshift_install_dir }}"

- name: remove cluster specific assets
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/.kube/{{ cluster_fqn }}"
    - "{{ cluster_metadata_dir }}/{{ cluster_fqn }}"
    - "{{ cluster_ssh_key_dir }}/{{ cluster_fqn }}"
    - "{{ cluster_ssh_key_dir }}/{{ cluster_fqn }}.pub"
    - "{{ openshift_install_dir }}/.env-{{ cluster_fqn }}.sh"
